### ISSUE TITLE
Can't render the Hardwaretree

### ISSUE THREAD

**Issue by MisterMountain** [moreamazingnick/icingaweb2-module-lshw#1]
Hi!

Nice talk yesterday ;-)
I couldn't wait to try it out and installed it on a local testing VM.
However, I can't render the hardware tree - maybe I am doing something wrong.

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/49c4ed70-1e13-4c9c-8573-cae64d9ffb2c">

`Undefined property: stdClass::$serial (LshwHardwareTree.php:103)`
`#0 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(103): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}()
#1 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(165): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->renderNic()
#2 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(80): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->renderNode()
#3 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(176): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->renderNodes()
#4 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(80): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->renderNode()
#5 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(176): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->renderNodes()
#6 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(80): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->renderNode()
#7 /usr/share/icingaweb2/modules/lshw/library/Lshw/Web/Widget/LshwHardwareTree.php(48): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->renderNodes()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(344): Icinga\Module\Lshw\Web\Widget\LshwHardwareTree->assemble()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(566): ipl\Html\HtmlDocument->ensureAssembled()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(420): ipl\Html\HtmlDocument->render()
#15 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php(101): ipl\Html\HtmlDocument->__toString()
#16 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php(455): Icinga\Module\Icingadb\Hook\ExtensionHook\ObjectDetailExtensionHook::loadExtensions()
#17 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ServiceDetail.php(35): Icinga\Module\Icingadb\Widget\Detail\ObjectDetail->createExtensions()
#18 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(344): Icinga\Module\Icingadb\Widget\Detail\ServiceDetail->assemble()
#19 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(566): ipl\Html\HtmlDocument->ensureAssembled()
#20 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#21 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#22 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#23 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\BaseHtmlElement->renderUnwrapped()
#24 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(390): ipl\Html\HtmlDocument->render()
#25 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(568): ipl\Html\HtmlDocument->renderUnwrapped()
#26 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(62): ipl\Html\HtmlDocument->render()
#27 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/Helper/ViewRenderer.php(970): ipl\Web\Compat\ViewRenderer->render()
#28 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#29 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(484): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#30 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#31 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch()
#32 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch()
#33 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#34 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#35 {main}`

I am running Icinga2 in Version 2.14.3 (I don't think this matters as it's a Web Module) with Icinga Web 2.12.2 and IcingaDB Web 1.1.3. All in a aarch64 Debian 12 VM.

**Comment by moreamazingnick** [comment]
Can you send me the output of lshw -json via mail? 
It will most likely be the case that I have to check for every element of it exists.

**Comment by moreamazingnick** [comment]
can you try out this release?:
https://github.com/moreamazingnick/icingaweb2-module-lshw/releases/tag/v0.1.1

**Comment by MisterMountain** [comment]
Yep. Looks much better now - the tree is getting rendered. Sent you the json output anyways.

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/ba29740e-307a-46b6-a22d-403976416e04">

**Comment by moreamazingnick** [comment]
Thanks
